// Copyright (C) 2022, Chain4Travel AG. All rights reserved.
//
// This file is a derived work, based on ava-labs code whose
// original notices appear below.
//
// It is distributed under the same license conditions as the
// original code from which it is derived.
//
// Much love to the original authors for their work.
// **********************************************************

// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	health "github.com/chain4travel/caminogo/api/health"
	rpc "github.com/chain4travel/caminogo/utils/rpc"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HealthClient is an autogenerated mock type for the Client type
type HealthClient struct {
	mock.Mock
}

// AwaitHealthy provides a mock function with given fields: ctx, freq, options
func (_m *HealthClient) AwaitHealthy(ctx context.Context, freq time.Duration, options ...rpc.Option) (bool, error) {
	ret := _m.Called(ctx, freq, options)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) bool); ok {
		r0 = rf(ctx, freq)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, freq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Health provides a mock function with given fields: _a0, _a1
func (_m *HealthClient) Health(_a0 context.Context, _a1 ...rpc.Option) (*health.APIHealthReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *health.APIHealthReply
	if rf, ok := ret.Get(0).(func(context.Context) *health.APIHealthReply); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.APIHealthReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Liveness provides a mock function with given fields: _a0, _a1
func (_m *HealthClient) Liveness(_a0 context.Context, _a1 ...rpc.Option) (*health.APIHealthReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *health.APIHealthReply
	if rf, ok := ret.Get(0).(func(context.Context) *health.APIHealthReply); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.APIHealthReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Readiness provides a mock function with given fields: _a0, _a1
func (_m *HealthClient) Readiness(_a0 context.Context, _a1 ...rpc.Option) (*health.APIHealthReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *health.APIHealthReply
	if rf, ok := ret.Get(0).(func(context.Context) *health.APIHealthReply); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.APIHealthReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
